### ISSUE TITLE
How does Pathspec work in git2-rs?

### ISSUE THREAD

**Issue by jeffparsons** [rust-lang/git2-rs#497]
I received some surprising results from `Pathspec::matches_path` (and related functions that use pathspecs). Specifically, it appears that wildcards are interpreted, but most of the other special syntax in pathspecs (https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec) isn't understood at all.

For example, a pathspec of `"my-directory"` will be considered by `matches_path` to match the path `"my-directory"`, but `":(icase)my-directory"` matches nothing, even though it should only be _more_ permissive about what it matches.

Note that passing these exact same pathspecs to the `git log` CLI matches as per the pathspec documentation linked above.

Is this a limitation of `libgit2`, a limitation of `git2-rs`, or am I using this wrong or misunderstanding how it's supposed to behave?

My use case involves excluding some paths (`":(exclude)the-thing"`) when performing a revwalk. I could implement this manually if necessary, but I'd like to first better understand how pathspecs are _meant_ to work in git2-rs.

Many thanks! 🙇

**Comment by alexcrichton** [comment]
Thanks for the report! My advice would be to browse the libgit2 documentation itself since this is just a wrapper around that library to see all the nitty-gritty here. If you've still got questions I'd also recommend bringing them up on the libgit2 issue tracker/discussion, they can probably help you out with specifics much better than we can!
