### ISSUE TITLE
Question: Is git blame -C[int] supported?

### ISSUE THREAD

**Issue by adaschevici** [rust-lang/git2-rs#501]
Hi, i've been going through the code examples and I'm looking at the one in `examples/blame.rs`.
I found this c [snippet](https://libgit2.org/libgit2/ex/HEAD/blame.html) that describes a similar approach and the -C flag seems to be an int. Not sure if that would emulate the -C[int]. Do the rust bindings take in an int as well?

**Comment by alexcrichton** [comment]
Thanks for the report! In general this library binds libgit2 so functionality is source from there. Some API bindings may be missing in which case a PR is more than welcome to fill out some bindings in Rust. Otherwise I suspect libgit2 supports this but I'm not precisely sure how, it may be good to confirm with them upstream though!

**Comment by adaschevici** [comment]
Thanks for the reply, I am having a look at the c libgit2 to see how that works, if it in fact supports the use case
