### ISSUE TITLE
error: unknown type name 'GIT_BEGIN_DECL'

### ISSUE THREAD

**Issue by kornelski** [rust-lang/git2-rs#723]
The version of libgit2-sys on crates.io has stopped building on my machine (upgrade to macOS 12 beta may have been related) for an odd reason: `GIT_BEGIN_DECL` is undefined. 

The issue is reliably reproducible, with both Apple clang and Homebrew gcc 11.

```
warning: In file included from libgit2/src/alloc.c:8:
warning: In file included from libgit2/src/alloc.h:11:
warning: /private/tmp/foo/target/debug/build/libgit2-sys-a2d40bc23ad2df82/out/include/git2/sys/alloc.h:13:1: error: unknown type name 'GIT_BEGIN_DECL'
warning: GIT_BEGIN_DECL
warning: ^
```

The problem appears to be fixed in the latest git of git2-rs (as of 7d1240514f8b5a2de935bf2b5ae20229257b943f), i.e:

```toml
git2 = "0.13.20"
```

doesn't build, but:

```toml
git2 = { git = "https://github.com/rust-lang/git2-rs" }
```

builds fine.

Therefore, can you release the latest changes?

**Comment by ehuss** [comment]
Hm.  We can definitely make a new release, but I am a bit surprised that it would make a difference because there haven't been any changes that would necessarily affect the build of libgit2-sys here.  (Changes listed [here](https://github.com/rust-lang/git2-rs/compare/0.13.20...7d12405).)  The only change that might be relevant is the vendored-openssl change, but that should only affect the linking of openssl, and only if you are using that feature (are you?).  I also wouldn't expect the use of openssl to change the parsing of a *header*.

Looking at the code, I don't see how that can fail.  The top of `sys/alloc.h` imports `git2/common.h` which defines `GIT_BEGIN_DECL`.  I don't see how it is possible for that to be undefined.

Does using `git2 = { git = "https://github.com/rust-lang/git2-rs", tag="0.13.20" }` still fail?  I'm wondering if there is some difference in how it is built as a "path-style" dependency (there are various subtle differences).

I'm also wondering, do you maybe have libgit2 installed via homebrew (or anywhere else)?  I'm just wondering, if maybe similar to #721 there is some interaction with the system-installed copy.

**Comment by kornelski** [comment]
Yeah, that's weird! The git dependency from the tag works, the crates.io dep doesn't.

**Comment by kornelski** [comment]
Oh, nevermind. `rm -rf ~/.cargo/registry/` fixed it. Sorry for the false alarm.
