### ISSUE TITLE
Error running tests after upgrade to libgit2-sys 0.12.23+1.2.0

### ISSUE THREAD

**Issue by taurr** [rust-lang/git2-rs#746]
In https://github.com/cargo-generate/cargo-generate, after upgrading `git2` to 0.13.22, tests no longer run due to

```
Git Error: invalid version 0 on git_proxy_options; class=Invalid (3)
```

Tracing this error leads to the upgrade of libgit2-sys, and seems to be an old issue: https://www.google.com/search?q=Git+Error%3A+invalid+version+0+on+git_proxy_options

**Comment by alexcrichton** [comment]
Can you provide some more information about how to reproduce and how minimize perhaps? The only usage of `git_proxy_options` should be constructed with the version field set to 1, so I'm not sure where this would be coming from.

**Comment by taurr** [comment]
Nor am I unfortunately, but it started failing immediately after upgrading to git2 version 0.13.21, and **only** on my linux setup (Manjoro/Arch) - not on windows 10.

After some searching and messing around I found that it ties down to the use of `libgit2-sys` version 0.12.23+1.2.0. A single revision back on that lib, and everything is ok again. Obviously it's a little difficult to downgrade once the offending version is on the system as the little `+` in the version allows it to pick the newer one :-)

**Comment by taurr** [comment]
As for reproduction, I was running `cargo test` against https://github.com/cargo-generate/cargo-generate

**Comment by srhb** [comment]
I did the mind-numbing bisect of libgit2 to find out what the culprit is, hoping that someone can pick up from here and realize what went wrong.

It appears the problem was introduced here:

https://github.com/libgit2/libgit2/pull/6012

Specifically in https://github.com/libgit2/libgit2/pull/6012/commits/72df17c659619707e4e5f27b2a51db60848a1d04

Doing a "slightly-sloppy-but-hey-it-builds"-revert appears to fix it: https://github.com/srhb/libgit2/commit/7d08801470ed377863c5b4b1a655b3f3ee980c22

**Comment by kim** [comment]
It might be that an incompatible version of libgit2 from the system package manager is picked up. Maybe try building with the `vendored-libgit2` feature?

**Comment by srhb** [comment]
You got me on the right track -- the problem was the opposite. I was pulling in a too-old version of git2-rs (and transitively the -sys component) which was incompatible with the newer libgit2 I was linking against. I had the problem backwards. Thank you! :smile:

**Comment by saethlin** [comment]
I think this is an ABI break in libgit2. I ran into exactly the same problem (mentioned above this comment, https://github.com/rust-lang/crater/pull/598) because I was trying to build a project with a dependency on a libgit2-sys intended for libgit2-1.1.0, but I was linking in libgit2 1.3.0. I feel like that ought to work, it's a minor version bump. So as far as I can tell, either libgit2 doesn't have ABI stability, or the libgit2 project is having a rough time trying to provide ABI stability.

In either case, I think this line: https://github.com/rust-lang/git2-rs/blob/f1a3e12c1bdda00d93be5ecf4959cf6f68d7e560/libgit2-sys/build.rs#L17 should be changed to `exactly_version` or perhaps `range_version` in case there's a newer patch release on the system.

Things work fine at the moment on the latest version of this crate(s), but it's possible that is only because it is caught up to the latest libgit2 release, so either a matching version or a vendored version is used. At the moment. I would like some more insurance that code continues to build as time passes :sweat_smile:

**Comment by jonasmalacofilho** [comment]
@saethlin,

> So as far as I can tell, either libgit2 doesn't have ABI stability, [...]

This seems to be the case (https://github.com/libgit2/libgit2/issues/6210#issuecomment-1035153614).

As that comment mentions, the precise API & ABI guarantees are documented in [`libgit2/libgit2/docs/api-stability.md`](https://github.com/libgit2/libgit2/blob/1327dbcf2a42/docs/api-stability.md?plain=1#L44-L62).  Relating to ABI stability, this is what they currently say (emphasis mine):

> * Our ABI is only considered stable through a minor release.
> 
>     * **Our ABI consists of actual symbol names in the library, the function signatures, and the actual layout of structures. These are only stable within minor releases, they are not stable within major releases (yet).**
>     * Since many FFIs use ABIs directly (for example, .NET P/Invoke or Rust), this instability is unfortunate.
>     * In a future major release, we will begin providing ABI stability throughout the major release cycle.
>     * ABI changes will be noted specially within a release's changelog.
> 
> * Point releases are generally only for bugfixes, and generally do not include new features. This means that point releases generally do not include new APIs. **Point releases will never break API, systems API or ABI compatibility.**

**Comment by taurr** [comment]
I believe and trust that this has been fixed by @joshtriplett in the commit mentioned above.

The problem was very repeatable on my machine, and has gone. Likewise there does not seem to be any new observations.

If it is still an issue, we can either reopen, or create a new issue.
