### ISSUE TITLE
Support for zdiff3 conflict-style from Git 2.35

### ISSUE THREAD

**Issue by taladar** [rust-lang/git2-rs#795]
Setting the new zdiff3 conflictStyle with
```
[merge]
    conflictStyle = zdiff3
```
in my global .gitignore leads to errors in e.g. cargo-deny like
```
2022-01-26 10:53:03 [ERROR] failed to fetch advisory database: git operation failed: unknown style 'zdiff3' given for 'merge.conflictstyle'; class=Checkout (20)
```

Since their source-code does not mention diff3 (the old value of that setting) but it uses git2-rs as a dependency and your source code does I assume it needs to be fixed on your end.

This is particularly annoying since that also means I can't use it with git itself.

**Comment by extrawurst** [comment]
That probably needs to to libgit2 upstream to support, or?

**Comment by taladar** [comment]
Possibly, I am not sure how your library (or libgit2) uses the conflict style.

**Comment by extrawurst** [comment]
like I said please open this conversation up in [libgit2](https://github.com/libgit2/libgit2) repo

**Comment by fbernier** [comment]
This has now been fixed in libgit2 with https://github.com/libgit2/libgit2/pull/6195.

Note to anyone ending up on this issue from googling around, it seems like  `cargo check` or `cargo build` on any rust project are currently returning an error whenever someone has the zdiff3  in their git config.

```
 unknown style 'zdiff3' given for 'merge.conflictstyle'; class=Checkout (20)
 ```
 
I guess the first step toward fixing this would be to update the libgit2 version used in git2-rs, so that it can eventually make its way into cargo.
