### ISSUE TITLE
Update git2-rs

### ISSUE THREAD

**Issue by basicfunc** [rust-lang/git2-rs#978]
Hey, `libgit2` recently released `v1.7.0` which adds shallow clone support, SHA256 support, adds Schannel support for Windows, and includes many other new features and bugfixes. Whereas this crate haven't had updated in months. Please update it.

**Comment by ehuss** [comment]
Thanks for the report! It has already been updated in https://github.com/rust-lang/git2-rs/pull/968, and a new release will come out soonish.  SHA256 support probably won't be supported since it is experimental. Shallow clone support will need someone to add the bindings, and PR's are welcome whenever new bindings are needed.  Closing as addressed by #968.
